name: Construir APK de Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar requerimientos
        run: pip install flet requests

      - name: Construir el APK
        run: flet build apk --verbose --android-permissions INTERNET --yes
          # Usamos un comando de Linux para responder "y" automáticamente si Flet pregunta algo
          yes | flet build apk --verbose --permissions INTERNET
        
      - name: Subir el APK final
        uses: actions/upload-artifact@v4
        with:
          name: App-Gottman-APK
          path: build/apk/**/*.apk
