name: Construir APK de Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Aceptar licencias de Android
        run: yes | sdkmanager --licenses || true

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: pip install flet requests

      - name: Compilar APK
        run: flet build apk --verbose --yes

      - name: Guardar el instalador
        uses: actions/upload-artifact@v4
        with:
          name: App-Gottman-APK
          path: build/apk/**/*.apk
