name: Construir APK de Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Flet y requerimientos
        run: |
          pip install flet requests

      - name: Construir el APK
        run: flet build apk

      - name: Subir el APK final
        uses: actions/upload-artifact@v4
        with:
          name: App-Gottman-APK
          path: build/apk/**/*.apk
